name: Build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  postgres-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Twir registry
        uses: docker/login-action@v3
        with:
          registry: registry.twir.app
          username: ${{ secrets.DOCKER_TWIR_LOGIN }}
          password: ${{ secrets.DOCKER_TWIR_PASSWORD }}

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.twir.app/twirapp/${{ env.app }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max